### PR TITLE
testDatas with XSD 2.1 + set cvsscore by severity

### PR DESCRIPTION
**Pull request by thib3113**
First, I include the PR #142 ,

second, I "generate" a `cvsscore` from the severity, the severity can be :
- Critical
- High
- Moderate
- Low
Specs : https://docs.npmjs.com/about-audit-reports#severity, and dependency-check, save it in lowercase .

So, I decide to convert : 
 - `Critical` to 10, because has npm say, critical need to be `Address immediately`
 - `High` to 7
 - `Moderate` to 5
 - `Low` to 3

I decide to do this, because I know some options use the cvsscore .

Also, I've add testDatas with vulnerabilities coming from NPM, with each severity .

And, I've change the default severity to `moderate` ( because it's the name from NPM ) ... But not sure if it's a good idea .

### CODE REVIEW

**Comment by Reamer** [comment]
Hi @thib3113,
i want  change this things:
 - drop support for dependency-check 5.0.0-M2
 - create a instance of ReportParser with a private variable SensorContext (remove static)
 - Create a new method in [DependencyCheckUtils](https://github.com/SonarSecurityCommunity/dependency-check-sonar-plugin/blob/master/sonar-dependency-check-plugin/src/main/java/org/sonar/dependencycheck/base/DependencyCheckUtils.java) which does nearly same like [cvssToSonarQubeSeverity](https://github.com/SonarSecurityCommunity/dependency-check-sonar-plugin/blob/master/sonar-dependency-check-plugin/src/main/java/org/sonar/dependencycheck/base/DependencyCheckUtils.java#L65) only in  opposite direction.

**Comment by thib3113** [comment]
@Reamer hum, 
`drop support for dependency-check 5.0.0-M2` : 
Hum, how did you want to do this ? technically ? not supporting the xsd 2.0 ? or add an error if  engineVersion() = 5.0.0-M2 ?

`create a instance of ReportParser with a private variable SensorContext (remove static)` : 
Not really understand what you want :/ . What will be `SensorContext` ? ( what I understand, SensorContext will be : `NodeContext` / `AssemblyContext` / etc , but because the file can contain multiple context, I think it's not what you want ) . Else, I'm not a java developper, so I can do simple things, but maybe not architechturing the app ( with correct way )

 `Create a new method in DependencyCheckUtils which does nearly same like cvssToSonarQubeSeverity only in opposite direction.`
Another times, I doesn't know how work the API of sonarqube, so I didn't understand :/ .

**Comment by thib3113** [comment]
Ok, so, maybe keep your PR, and I'll add datas and test for node ? ( And this time can remove the 5 old commits in this PR ... )

**Comment by Reamer** [comment]
It would be nice if you create a PullRequest, with a really small node example project under this path https://github.com/SonarSecurityCommunity/dependency-check-sonar-plugin/tree/master/examples
Goals:
 - Other people (including me) will be able to create node reports
 - The small node project should include vulnerabilities

**Comment by thib3113** [comment]
No problem about that . Maybe just some questions : 
 - Did I need to include the `node_modules`, or just the package.json ( and package-lock.json ) . In fact dependency check (cli) will read the package-lock.json, and try to read each package's package.json .

So, with the dependencies ( the `node_module` folder ), the project will store really lot of files : maybe not good, but you don't need to install npm/node or other ( I thing ).

Of just the package.json => you need to run `npm install` before analysing it .

For the moment, I use this dependency : 
- open:0.0.5 => critical from npm
- tar:4.4.0 => high from npm
- lodash:4.17.10 => moderate from npm
- braces:2.3.0 => low from npm

Need I to include some vulnerabilities from NVD too ? ( or it's like the other ? )

**Comment by Reamer** [comment]
The node_module folder shouldn't included in this git-repository. `npm` as a requirement is absolutely okay. `npm install`is quiet similar to `mvn package`. It would be nice, if this example node project also includes some vulnerabilities from NVD.

**Comment by thib3113** [comment]
@Reamer here is it : #145

**Comment by Reamer** [comment]
no need for extra nodejs test data 
set cvsscore by serverity implemented with https://github.com/SonarSecurityCommunity/dependency-check-sonar-plugin/commit/fb6e4c4dc4d4c7714fea28e557a0833dce62d268

Big Thanks to @thib3113 for helping me. In next days I'll create a new release of this plugin which should solve #140 #135

**Pull request closed without merging**
