### PR TITLE
Add test data for node.Js report

### PR DESCRIPTION
**Pull request by thib3113**
Following this issue #135 I'm adding some tests datas

### CODE REVIEW

**Comment by Reamer** [comment]
Hi @thib3113 
this is quite interesting, it seems that vulnerabilities found via NPM have no cvss score. (Take a look into comment https://github.com/jeremylong/DependencyCheck/issues/1366#issuecomment-423715087)
What would be a good solution for this case?
Ignoring NPM vulnerabilities or set a default score (0-10).

**Comment by Reamer** [comment]
Please pretty  print your big xml file. Possible tools: https://stackoverflow.com/questions/16090869/how-to-pretty-print-xml-from-the-command-line

**Comment by thib3113** [comment]
About the big file, I've just add it to show how big can become a node.js analysis . So just adding this to test an "unmodified" report . But I can pretty print it without problems ( but tomorrow ) .

About the npm part, I know `npm audit` return a vulnerability level ( telling if vulnerability is important, medium or low ), so it's will maybe be updated in dependency check tool ( node.js analyser is buggy some times, and show really lot of warnings ) . So, for the moment, set it to middle score by default ? To tell it's not a low vulnerability, and not a high vulnerability, just unknown level. 

I'll read your link tomorrow too .

**Comment by thib3113** [comment]
So, after some research, it seems the version 5.0.0-SNAPSHOT ( directly from the git, with commit https://github.com/jeremylong/DependencyCheck/commit/c747bac91ff06f234c76c55178a3f70036549727 ) , seems to produce this in the xml : 
```
<vulnerability source="NPM">
                    <name>786</name>
                    <severity>low</severity>
                    <cwes></cwes>
                    <description>Versions of `braces` prior to 2.3.1 are vulnerable to Regular Expression Denial of
                        Service (ReDoS). Untrusted input may cause catastrophic backtracking while matching regular
                        expressions. This can cause the application to be unresponsive leading to Denial of Service.
                    </description>
                    <references>
                        <reference>
                            <source>Advisory 786: Regular Expression Denial of Service</source>
                            <name>- [GitHub
                                Commit](https://github.com/micromatch/braces/commit/abdafb0cae1e0c00f184abbadc692f4eaa98f451)
                            </name>
                        </reference>
                    </references>
                    <vulnerableSoftware>
                        <software>cpe:2.3:a:*:braces:\&lt;2.3.1:*:*:*:*:*:*:*</software>
                    </vulnerableSoftware>
                </vulnerability>
```
As you can see, a `severity` node is added, with the level, but undocumented in the xsd ( I've open an issue https://github.com/jeremylong/DependencyCheck/issues/1873 about it )

**Comment by Reamer** [comment]
Hi @thib3113,
I added a small Workaround till dependency-check-5.0.0 is released. Please add some more asserts in your test method - in special the "workaround values". https://github.com/SonarSecurityCommunity/dependency-check-sonar-plugin/pull/141

**Comment by thib3113** [comment]
Hi @Reamer , here is it, I add more assertions, testing jquery, brace, and kind of ( jquery contain a NVD vulnerability, brace a NPM vulnerability, and kind-of without vulnerabilities ) . 

( I'm not a java developper, so I didn't really know how to test only this 3 dependencies on the big report, so I've done 3 basics conditions )

**Comment by Reamer** [comment]
All good, thanks for your work.

**Pull request merged**
