### PR TITLE
#15 Aggregation of dependency-check metrics

### PR DESCRIPTION
**Pull request by reallyinsane**
#15 
This should be the fix for the problem. The cause of the missing aggregation is that this should be done by a MeasureComputer which is missing. Once you have this you can aggregate metrics on directory, module and project level. You just need to collect the metrics of the children.
 Therefore I changed the creation of the metrics to be on the pom.xml and not the module. Adding metrics to modules will be deprecated anyway.

You can also have look at [mathan-dependency-updates-sonar-plugin](https://github.com/reallyinsane/mathan-dependency-updates-sonar-plugin) which had the same problem.

### CODE REVIEW

**Comment by reallyinsane** [comment]
Could also solve #106 as issues are stored on pom.xml with this pull request.

**Comment by Reamer** [comment]
Hi @reallyinsane,
thanks for the Pull Request. I rewrote the plugin architecture in #99.
You are right, metrics on modules are deprecated. Therefore I programmed my own calculator in https://github.com/SonarSecurityCommunity/dependency-check-sonar-plugin/pull/99/files#diff-3bcfe0eef76fd051616a4854cf7408a9R195 , which is not optimal.
Thanks for the hint with MeasureComputer, i will take a look.

**Comment by Reamer** [comment]
Hi @reallyinsane,
I used you hint for computing measures in #124. It's important for me that project without pom.xml or gradle.build can use this plugin. Issues should link to project as before.

**Comment by Reamer** [comment]
Merged with  #124

**Pull request closed without merging**
